
---
output: 
  html_document:
    toc: true
    toc_float: true
    theme: simplex
---

# Summary 

An Epidemiologist and Clinical Research Analyst with nearly a decade of experience across dental entrepreneurship and scientific research focused on statistical data. A passion for leveraging research data to assess and improve healthcare, coupled with a specialization in preventative medicine to control chronic diseases like cancer, cardiovascular, and neurological conditions that impact the population motivates me. The capacity to collaborate across medical and dental specialists, as well as communicate with a diverse group of patients has enabled me to champion team leadership

------------------------------------------------------------------------------------------------------

# Work Experience

**New York Presbyterian Hospital, Department of Neurology** 

**_Research Assistant (May,2019 to May,2020)_**  
  
◆	Gathered/reviewed/summarized literature from scientific journals: PubMed/JAMA that identified gaps in previous research 

◆	Built Logistic Regression models using SAS; assessed association of Ischemic stroke/Subarachnoid hemorrhage with risk factors i.e., Diabetes Mellitus, Pre-existing Hypertension, Smoking, Chronic Renal Diseases 

o	Analyzed Stroke trend in young adults: 2004-2015; performed exploratory data analysis on SPARCS dataset using SAS

	Created visualizations of findings using R; wrote/reviewed drafts—reports/posters/manuscripts 

o	Presented Research findings to 50+ researchers/200+ graduate students at Mailman School of Public Health

◆	Created datasets for analysis; performed data cleaning; identified/generated key features explaining the stroke risk factors 

o	Built logistic regression models using SAS and R; determined prevalence of stroke 2004-2015

o	Identified association between stroke/risk factors, i.e., Diabetes, Hypertension, Smoking, and Chronic Kidney disease 

	Concluded: Subarachnoid Hemorrhage prevalence—young adults; Ischemic Stroke prevalence—older individuals

	Determined that the prevalence of Ischemic Stroke/Subarachnoid Hemorrhage has increased over time

	Assessed Strokes are more prevalent among females/African Americans/not of Spanish/Hispanic origin 

	Identified associations: Ischemic Stroke/Diabetes/Hypertension/Smoking; Subarachnoid Hemorrhage/Hypertension 

◆	Created metrics/visualizations using ggplot2/R to summarize results of statistical analyses; presented results to stakeholders

o	Allowed identification of patterns within the data set; facilitated comprehension of findings to the stakeholders 


**Columbia University Mailman School of Public Health**

**_Graduate Teaching Assistant (August,2019 to May,2020)_** 
  
Graduate Teaching Assistant for 2 studios- _Global and Developmental Perspectives, Integration of Science and  Practice_.
  
◆ Facilitated classroom discussions focused on academic and intellectual topics to further students' critical thinking skills as well as an understanding of the materials presented, providing academic support to 400+ students

◆ Evaluated student assignments, projects, exams, and assisted students with course material during regular office hours

◆ Assisted in adapting the course to be taught and administered entirely online due to the COVID-19 pandemic

**Dr. Ekta’s Dental Solutions, Haryana, India** 

**_President and Founder (July 2013 to July 2018)_**                                                                                                                   
◆ Appointed, managed and led a team of 5 Dental specialists, 4 Dental Auxiliary staff, 5+ Interns that ensured the effective running of the dental operatory and improved the dental operation time 

◆ Clearly defined the dental clinic's code of conduct and enforced specific guidelines in a constructive manner which led to improved staff relationship and enhanced the productivity by 20%

◆ Consulted with patients and analyzed patient data to determine patient needs and treatment goals

◆ Effectively conducted oral/maxillofacial and pre-prosthetic surgeries, implant surgeries, root canal treatment, scaling and root planning, smile designing, restorations on 5000+ patients

◆ Collected, measured, and analysed the patient data, to develop a much clearer picture of the practice's performance, and compared the practice's data to the national statistics to identify the areas of improvement

◆ Coordinated and led weekly meeting with the staff and discussed ways to improve the practice like social media marketing, having a dental assistant assigned per chair in the office enabling four-handed dentistry, organizing dental camps diagnosing more number of patients with dental diseases and motivating them for dental treatment, following-up with patients' appointments through emails, text messages, and phone calls, improving the revenue by 25%

◆ Conducted research on defects, diseases, and disorders affecting the oral and/or facial regions

**Swami Devi Dayal Hospital and Dental College, Haryana, India**  

**_Research Associate (December 2015 to November 2017)_**

◆	Managed/cleaned/optimized hospital databases using MS Access; helped recruit from community health clinics

o	Interviewed/assessed/assisted with randomized clinical trials; administered qualitative/quantitative data collection

o	Collected relevant patient data; analyzed using SAS to produce reports/graphs, communicated results clearly

◆	Evaluated dental caries change status over 2 years—school children; examined 407 children ages 7-9: DMFT status

o	Educated children: desired oral health behavior via hand-outs after examination; emphasized brushing techniques/diet 

o	Referred those in need of treatment to the dental clinics; examined the same group after 2 years— determined DMFT status 

	Used Paired t-test to compare mean DMFT score at baseline—revealed 78% of the children had caries

	Assessed significant increase in DMFT scores of children; necessitated rigorous preventive strategies 

**_Research Assistant (December 2012 to November 2015)_**

◆	Assessed a random sample of 500 subjects to determine the level/cause of edentulousness: middle-aged/elderly population 

o	Used chi-squared tests to examine the association with smoking/tobacco chewing, socioeconomic status, diet, BMI

	Determined higher level to be in subjects with low socioeconomic status—lack of dental awareness

	Mixed diet; High BMI— strongly associated 

o	Organized several dental education and motivation camps at the community level for elderly patients

o	Determined the main causes of edentulousness

	Dental Caries—37.4%, Combination of Dental Caries/Periodontal Disease: 12.2% 

◆	Conducted a descriptive cross-sectional study on 160 subjects to assess the oral health status of Hemophilic Children 

o	Performed statistical analysis using SAS: observations were statistically analyzed using the Chi-square test

	Concluded oral hygiene status of hemophilic children—poor; dental caries prevalence: 76.3%

o	Developed effective oral health promotional/interventional strategies to combat the prevalence of dental diseases

**_Clinical Intern (November 2011 to November 2012)_**

◆ Completed compulsory rotational internship; gained clinic training—various specialties of dentistry 

o	Scheduled appointments, maintained records, and conducted dental treatments on 1000+ patients within one year

◆	Developed/implemented dental care plans for 40+ patients/week; monitored progress/maintained records to evaluate 

◆	Planned/coordinated/organized intensive 3-day dental/medical health awareness campaign at Indo-Tibetan Border Police

o	Treated 500+ patients within 3 days

◆	Assisted with a research study to study the impact of the mid-day meal programs

o	Found reduction in absenteeism in schools by 60% after the implementation of midday meal programs

------------------------------------------------------------------------------------------------------

# Education

**Columbia University Mailman School of Public Health, New York, NY**

**_Master of Public Health in Epidemiology | Certificate: Epidemiology of Chronic Diseases: May 2020_**                                              

Relevant coursework:
  
_Epidemiology_: Research Methods & Applications, Design and Conduct of Observational Epidemiology, Principles of Epidemiology III- Applied Epidemiologic Analysis, Application of Epidemiologic Research Methods using SAS, Chronic Disease Epidemiology, Cancer Epidemiology

_Biostatistics_: Analysis of Categorical Data, Data Science I(R programming), Relational Databases And SQL Programming, Data Science II (Machine Learning), Applied Regression I, Applied Regression II.

_Other relevant courses_: Foundation of Public Health, Global and Developmental Perspectives, Public Health Interventions, Determinants of Health, Health Systems, Leadership Development, Integration of Science and Practice, Public Health GIS

**Kurukshetra University, Haryana, India**

**_Bachelor of Dental Surgery Equivalent to Doctor of Dental Surgery (DDS): Graduated- November 2012_** 

Coursework: 

_Year 1_: General Human Anatomy including Embryology and Histology, General Human Physiology and Biochemistry, Nutrition and Dietetics, Dental Materials

_Year 2_: Dental Anatomy, Embryology and Oral Histology, General Pathology and Microbiology, General and Dental Pharmacology and Therapeutics, Preclinical Prosthodontics and Crown & Bridge, Preclinical Conservative Dentistry

_Year 3_: General Medicine, General Surgery, Oral Pathology and Oral Microbiology, Public Health Dentistry

_Year 4_: Oral Medicine and Radiology, Pediatric and Preventive Dentistry, Orthodontics and Dentofacial Orthopedics, Periodontology, Prosthodontics and Crown and Bridge, Conservative Dentistry and Endodontics, Oral and Maxillofacial Surgery

------------------------------------------------------------------------------------------------------

# Skills and Certifications

◆ **Programming:** SAS, STATA, SQL, R, QGIS

◆ **Database Management tools:** MS Access, MySQL

◆ **Data Visualisation tools:** Shiny, Plotly, ggplot2, Tableau, Flexdashboard 

◆ **Microsoft Office Suite:** MS-Word, MS-Excel, MS-PowerPoint, MS Access, MS Outlook

◆ **Certifications:** HIPAA, CITI, Epidemiology of Chronic Diseases, Data Science- R basics, Advanced SQL for Data Scientists, Tableau 10 for Data Scientist

◆ **Languages:** English, Hindi, Punjabi.

------------------------------------------------------------------------------------------------------

# Volunteer Leadership 

**Enable, Columbia University** 

**Founder and President** 

Enable is a student organisation at Columbia University established with a mission to destigmatize disability of all forms.

Role: 
◆ Identified the needs of students with disabilities through one-on-one and focus group interviews 

◆ Registered the organisation, recruited the first E-board of the organisation

◆ Planned, organised and executed events to raise awareness on disability and destigmatize disability

◆ Monitored semesterly expenses per event via keeping receipts from vendors and submitted reimbursements to the Office of Student Affairs to ensure the stable functioning of the organization

◆ Collaborated and invited other organizations for on-campus events for community engagement

**Columbia University Irving Medical Center**

**Covid-19 Studnet Service Corps**

◆ Responsible for designing and organising accessible information materials for COVID-19 patients and general public to better convey the important information to people with limited health literacy skills

◆ Reviewing and summarising literature from scientific journals and creating a database of the reviewed literature